name: articles_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  riverpod_annotation: ^2.0.4
  equatable: ^2.0.5
  flutter_riverpod: ^2.3.4
  dio: ^5.1.1
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  flutter_widget_from_html: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_test: ^1.0.1
  riverpod_generator: ^2.2.1
  build_runner: ^2.3.3
  very_good_analysis: ^3.1.0
  test_coverage_badge: ^0.2.0




flutter:
  uses-material-design: true


